### ISSUE TITLE
Errors are thrown if network is down or Circle is unreachable

### ISSUE THREAD

**Issue by cliffrowley** [cliffrowley/atom-circle-ci#1]
Usually happens when my Mac goes to sleep, but will almost certainly happen if the Circle CI service is available for whatever reason (e.g. maintenance).

```
Uncaught Error: connect ENETDOWN
Uncaught Error: socket hang up
```

As well as popping up the console, the package also stops checking for updates.

**Comment by alansikora** [comment]
This was fixed with PR #16.
