### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by framerate** [cliffrowley/atom-circle-ci#14]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/framerate/.atom/packages/circle-ci/lib/circle-ci.coffee:9:7)
```

**Comment by cliffrowley** [comment]
Thanks @framerate - I thought I'd fixed this, perhaps I forgot to publish.  I will check!

**Comment by cliffrowley** [comment]
@framerate thanks again.  Apparently I didn't fix this at all (I was thinking of something else).  I'm not sure when I will get a chance to update this as I don't really use Circle CI any more (I no longer work with the client who did at the time).  At some point I intend to bundle up the various CIs I use (and have used) into a general 'CI' package, but no ETA on that either.  Feel free to submit a PR.  I'm also happy to share collaborative permissions on this repo :-)

**Comment by framerate** [comment]
hmm. bummer! I keep promising to fix OSS bugs like this but never seem to get around to them with my own workload!

My coffee is a bit rusty, but I might be able to take a look. It's PROBABLY a oneline fix I'd imagine?

**Comment by tiwilliam** [comment]
Fixed in latest release.
