### ISSUE TITLE
Does not work behind the proxy

### ISSUE THREAD

**Issue by alexei-led** [cliffrowley/atom-circle-ci#27]
It would be nice, if you can fix it. You can try to read system defined environment variable `https_proxy`. 

```
var Client = require('node-rest-client').Client;

// configure proxy
var options_proxy = {
    proxy: {
        host: "proxy.foo.com",
        port: 8080,
        user: "proxyuser",
        password: "123",
        tunnel: true
    }
};

var client = new Client(options_proxy);
```

**Comment by cliffrowley** [comment]
Unfortunately I am no longer using Circle CI so my support for this plugin is limited to contributions.  I am happy to add contributors, should you be willing to jump in :-)

**Comment by himynameisdave** [comment]
@cliffrowley I would potentially be interested in taking over this project if you are interested!

**Comment by cliffrowley** [comment]
@himynameisdave very much so - it's a shame I haven't been able to keep up with it, but you know how it is - it's difficult to maintain something you aren't using!
